# Site wide configuration

title:            Yeakel Group
locale:           en_US
url:              //jdyeakel.github.io
# url:              http://localhost:4000


# Jekyll configuration

permalink:   /:categories/:title/
markdown:    kramdown
# highlighter: rouge
syntax_highlighter: coderay
sass:
  sass_dir: _sass
  style: compressed
plugins:
  - jekyll-sitemap

kramdown:
  auto_ids: true
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..6
  # enable_coderay: true
    # coderay:
    # coderay_line_numbers: nil
    # coderay_css: style

# Site owner
owner:
  name: Justin D. Yeakel
  avatar: justin-web.jpg
  bio: "Assoc. Prof. @ UC Merced <br>
  Biology Program Chair <br>
  Ext. Prof. @ Santa Fe Institute"
  email: jdyeakel@gmail.com 
  disqus-shortname: 
  twitter: #username
  facebook: #username
  google:
    plus: #jdyeakel
    analytics: #UA-55642416-1 
    verify: 
    ad-client: 
    ad-slot: 
  bing-verify: 
  github: jdyeakel
  stackoverflow: #http://stackoverflow.com/users/123456/username
  linkedin: #username
  instagram: #username
  lastfm: #username
  tumblr: #username
  pinterest: #username
  foursquare: #username
  steam: #username
  dribbble: #username

include: [".htaccess"]
exclude: ["lib", "config.rb", "Capfile", "config", "log", "Rakefile", "Rakefile.rb", "tmp", "less", "*.sublime-project", "*.sublime-workspace", "test", "spec", "Gruntfile.js", "package.json", "node_modules", "Gemfile", "Gemfile.lock", "LICENSE", "README.md", "*.jekyll-cache","vendor"]
