# Site wide configuration

title:            Justin D. Yeakel
locale:           en_US
url:              http://jdyeakel.github.io
#url:              http://localhost:4000


# Jekyll configuration

permalink:   /:categories/:title/
markdown:    kramdown
highlighter: pygments
sass:
  sass_dir: _sass
  style: compressed
gems:
  - jekyll-sitemap

kramdown:
  auto_ids: true
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..6
  use_coderay: false


# Site owner
owner:
  name: Justin D. Yeakel
  avatar: Justin_Web.jpg
  bio: "Omidyar Postdoctoral Fellow at the Santa Fe Institute"
  email: 
  disqus-shortname: 
  twitter: jdyeakel
  facebook: #username
  google:
    plus: jdyeakel
    analytics: 
    verify: 
    ad-client: 
    ad-slot: 
  bing-verify: 
  github: jdyeakel
  stackoverflow: #http://stackoverflow.com/users/123456/username
  linkedin: #username
  instagram: #username
  lastfm: #username
  tumblr: #username
  pinterest: #username
  foursquare: #username
  steam: #username
  dribbble: #username

include: [".htaccess"]
exclude: ["lib", "config.rb", "Capfile", "config", "log", "Rakefile", "Rakefile.rb", "tmp", "less", "*.sublime-project", "*.sublime-workspace", "test", "spec", "Gruntfile.js", "package.json", "node_modules", "Gemfile", "Gemfile.lock", "LICENSE", "README.md"]
