name: GitHub Pages Build

on:
  push:
    branches:
      - master  # Replace 'master' with your default branch name if different.

jobs:
  build:
    runs-on: ubuntu-22.04  # Explicitly use Ubuntu 22.04 instead of the latest version.

    steps:
      # Step 1: Check out your repository
      - name: Checkout Code
        uses: actions/checkout@v3

      # Step 2: Set up Ruby
      - name: Setup Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.1'  # GitHub Pages uses Ruby 3.1.x.

      # Step 3: Install dependencies
      - name: Install Dependencies
        run: |
          gem install bundler
          bundle install

      # Step 4: Build the Jekyll site
      - name: Build Site
        run: bundle exec jekyll build

      # Step 5: Deploy to GitHub Pages
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./_site
